--  This migration creates the initial schema for a student course registration system
-- Using PostgreSQL:17


CREATE TABLE users (
                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username       VARCHAR(100) NOT NULL UNIQUE,
                        email          VARCHAR(255) NOT NULL UNIQUE,
                        password_hash  VARCHAR(255) NOT NULL,
                        is_active      BOOLEAN NOT NULL DEFAULT TRUE,
                        last_login_at  TIMESTAMPTZ,

                       created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
                       created_by     BIGINT REFERENCES users(id),
                       updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
                       updated_by     BIGINT REFERENCES users(id)
);

CREATE TABLE roles (
                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       role_name    VARCHAR(30) NOT NULL UNIQUE,
                       description  VARCHAR(255),

                       created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
                       created_by   BIGINT REFERENCES users(id),
                       updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
                       updated_by   BIGINT REFERENCES users(id)
);

CREATE TABLE user_roles (
                            user_id     BIGINT NOT NULL REFERENCES users(id),
                            role_id     BIGINT NOT NULL REFERENCES roles(id),

                            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
                            created_by  BIGINT REFERENCES users(id),

                            PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_roles_role ON user_roles(role_id);

CREATE TABLE students (
                          id              BIGINT PRIMARY KEY REFERENCES users(id),
                          student_number  VARCHAR(20) NOT NULL UNIQUE,
                          first_name      VARCHAR(100) NOT NULL,
                          last_name       VARCHAR(100) NOT NULL,
                          date_of_birth   DATE,
                          phone           VARCHAR(30),
                          address         VARCHAR(255),
                          status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

                          created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
                          created_by      BIGINT REFERENCES users(id),
                          updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
                          updated_by      BIGINT REFERENCES users(id)
);

CREATE TABLE staff (
                       id               BIGINT PRIMARY KEY REFERENCES users(id),
                       employee_number  VARCHAR(20) NOT NULL UNIQUE,
                       first_name       VARCHAR(100) NOT NULL,
                       last_name        VARCHAR(100) NOT NULL,
                       title            VARCHAR(100),
                       department       VARCHAR(100),
                       hire_date        DATE,

                       created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
                       created_by       BIGINT REFERENCES users(id),
                       updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
                       updated_by       BIGINT REFERENCES users(id)
);

CREATE TABLE terms (
                       id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name                VARCHAR(50) NOT NULL UNIQUE,
                       start_date          DATE NOT NULL,
                       end_date            DATE NOT NULL,
                       registration_start  TIMESTAMPTZ,
                       registration_end    TIMESTAMPTZ,
                       is_active           BOOLEAN NOT NULL DEFAULT TRUE,

                       created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
                       created_by          BIGINT REFERENCES users(id),
                       updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
                       updated_by          BIGINT REFERENCES users(id)
);

CREATE TABLE courses (
                         id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         code          VARCHAR(20) NOT NULL UNIQUE,
                         title         VARCHAR(200) NOT NULL,
                         description   TEXT,
                         credit_hours  SMALLINT NOT NULL,
                         department    VARCHAR(100),
                         is_active     BOOLEAN NOT NULL DEFAULT TRUE,

                         created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
                         created_by    BIGINT REFERENCES users(id),
                         updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
                         updated_by    BIGINT REFERENCES users(id)
);

CREATE INDEX idx_courses_department ON courses(department);

CREATE TABLE course_prerequisites (
                                      course_id        BIGINT NOT NULL REFERENCES courses(id),
                                      prerequisite_id  BIGINT NOT NULL REFERENCES courses(id),

                                      created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
                                      created_by       BIGINT REFERENCES users(id),

                                      PRIMARY KEY (course_id, prerequisite_id),
                                      CHECK (course_id <> prerequisite_id)
);

CREATE TABLE course_offerings (
                                  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  course_id           BIGINT NOT NULL REFERENCES courses(id),
                                  term_id             BIGINT NOT NULL REFERENCES terms(id),
                                  section_number      VARCHAR(10) NOT NULL DEFAULT '001',
                                  instructor_id       BIGINT REFERENCES staff(id),
                                  capacity            INT NOT NULL,
                                  waitlist_capacity   INT NOT NULL DEFAULT 0,
                                  room                VARCHAR(50),
                                  days_of_week        VARCHAR(20),
                                  start_time          TIME,
                                  end_time            TIME,
                              status              VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',

                                  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
                                  created_by          BIGINT REFERENCES users(id),
                                  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
                                  updated_by          BIGINT REFERENCES users(id),

                                  UNIQUE (course_id, term_id, section_number)
);

CREATE INDEX idx_offerings_term ON course_offerings(term_id);
CREATE INDEX idx_offerings_instructor ON course_offerings(instructor_id);

CREATE TABLE enrollments (
                             id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             student_id         BIGINT NOT NULL REFERENCES students(id),
                             offering_id        BIGINT NOT NULL REFERENCES course_offerings(id),
                             course_id          BIGINT NOT NULL REFERENCES courses(id),
                             term_id            BIGINT NOT NULL REFERENCES terms(id),
                              status             VARCHAR(20) NOT NULL DEFAULT 'ENROLLED',
                             waitlist_position  INT,
                             grade              VARCHAR(5),
                             enrolled_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
                             dropped_at         TIMESTAMPTZ,

                             created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
                             created_by         BIGINT REFERENCES users(id),
                             updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
                             updated_by         BIGINT REFERENCES users(id)
);

CREATE INDEX idx_enrollments_offering ON enrollments(offering_id);
CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE UNIQUE INDEX uq_enrollment_active_per_course_term
    ON enrollments (student_id, course_id, term_id)
    WHERE status IN ('ENROLLED', 'WAITLISTED');

CREATE TABLE activity_logs (
                               id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               actor_user_id   BIGINT REFERENCES users(id),
                               action          VARCHAR(100) NOT NULL,
                               entity_type     VARCHAR(50) NOT NULL,
                               entity_id       BIGINT,
                               details         JSONB,
                               ip_address      INET,
                               created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_activity_logs_actor ON activity_logs(actor_user_id);
CREATE INDEX idx_activity_logs_entity ON activity_logs(entity_type, entity_id);
CREATE INDEX idx_activity_logs_created_at ON activity_logs(created_at);

CREATE TABLE refresh_tokens (
                                id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                token_hash        VARCHAR(255) NOT NULL,
                                jti               VARCHAR(64) NOT NULL UNIQUE,
                                family_id         VARCHAR(64) NOT NULL,
                                parent_jti        VARCHAR(64),
                                device_id         VARCHAR(255),
                                ip_address        INET,
                                user_agent        VARCHAR(500),
                                issued_at         TIMESTAMPTZ NOT NULL,
                                expires_at        TIMESTAMPTZ NOT NULL,
                                revoked_at        TIMESTAMPTZ,
                                replaced_by_jti   VARCHAR(64),
                                reuse_detected    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_refresh_tokens_family_id ON refresh_tokens(family_id);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);
CREATE INDEX idx_refresh_tokens_parent_jti ON refresh_tokens(parent_jti);