spring:
  application:
    name: student-course-registration-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}



security:
  jwt:
    secret: ${JWT_SECRET:wCUtLESdQf2IchnZ/rA8J5oDFMza9HPX6vL1Hr9rNhM=}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}
    refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
